version: '3'
services:
  dofbot:
    build: .
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/yahboom_backup:/root/yahboom_backup
      - /dev:/dev
    stdin_open: true
    tty: true
    container_name: dofbot_container
